## the params for app
app:
  home: /home/appops
  health:
    port:
    expectedStartTime: 200
    check:
    status:
    online:
    offline:
  params:
    jvmExtra:
    mainClassName:
    xms: "512"
    xmx: "512"
    xdebugAddress:
  spec:
    autoscale: none
    replicas: 1
    resource: x-small
  strategy:
    pauseType: all
    stepsTotal: 1
  advanced:
    ingress:
      enabled: false
      annotations: {}

  ## checkTime*checkPeriod is the livenessProbe check initialDelaySeconds
  ## the app container will startup will check the memcached for checkTime every checkPeriod
  checkTime: 6
  checkPeriod: 5
  envs: []

horizon:
  application:
  cluster:
  priority:

env:
  environment: ""
  region:
  namespace:
  baseRegistry:
  ingressDomain:

# some default config for health check
health:
  livenessProbe:
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 2

  online:
    timeout: 30
    sleep: 10
  offline:
    timeout: 5
    sleep: 10
    retry: 2

# artifacts image
image: ""

# tags
tags: {}

resources:
  tiny:
    cpu: 500
    memory: 1024
  x-small:
    cpu: 1000
    memory: 2048
  small:
    cpu: 2000
    memory: 4096
  middle:
    cpu: 4000
    memory: 8192
  large:
    cpu: 8000
    memory: 16384
  flexible:
    cpu: "{{ .Values.app.spec.cpu | default 500 }}"
    memory: "{{ .Values.app.spec.memory | default 1024 }}"

oversale:
  cpu:
    online: 30
    others: 40
  memory:
    delta: 256

# affinity, Ref: https://kubernetes.io/zh/docs/concepts/scheduling-eviction/assign-pod-node/
affinity:
  # podAntiAffinity
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: cloudnative.music.netease.com/cluster
            operator: In
            values:
            - "{{ .Values.horizon.cluster }}"
        topologyKey: "kubernetes.io/hostname"

# dnsPolicy. the kubernetes' default value is "ClusterFirst".
# In order to not use core-dns or kube-dns, we set this value to "Default".
# Ref: https://kubernetes.io/zh/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
dnsPolicy: Default

# podExtra, podSpec extra field, you can define fields which is not exactly defined. For example:
# podExtra:
#   nodeSelector:
#     nodeKey: nodeValue
podExtra: {}

# containerExtra, container extra field
containerExtra: {}

# restart time, used to restart this application
restartTime:

