apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.horizon.cluster }}
  labels:
{{- include "podLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.spec.replicas }}
  selector:
    matchLabels:
{{- include "podLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "podLabels" . | nindent 8 }}
      {{- $podAnnotations := include "podAnnotations" . }}
      {{- if $podAnnotations }}
      annotations: {{- $podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      ####### podExtra #######
      {{- with .Values.podExtra }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      ####### end podExtra #######
      ####### HostAlias #######
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      ####### end HostAlias #######
      ########## affinity ############
      {{- if .Values.affinity }}
      affinity: {{ tpl (.Values.affinity | toYaml ) (.) | nindent 8 }}
      {{- end }}
      ########## end  affinity ############
      ########## dnsPolicy ############
      dnsPolicy: {{ .Values.dnsPolicy }}
      ########## end dnsPolicy ############
      containers:
      - name: {{ .Values.horizon.cluster }}
        image: {{ .Values.image }}
        ####### containerExtra #######
        {{- with .Values.containerExtra }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        securityContext:
          runAsNonRoot: true
        ####### end containerExtra #######
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        {{- with .Values.horizon.application }}
          - name: HORIZON_APPLICATION
            value: "{{ . }}"
        {{- end }}
        {{- with .Values.horizon.cluster }}
          - name: HORIZON_CLUSTER
            value: "{{ . }}"
        {{- end }}
        {{- with .Values.env.environment }}
          - name: HORIZON_ENVIRONMENT
            value: "{{ . }}"
        {{- end }}
        {{- range $index, $item :=.Values.app.envs }}
          - name: {{ $item.name | quote }}
            value: {{ $item.value | quote }}
        {{- end }}
        ######### resources #########
        resources: {{ include "resources" . | nindent 10 }}
        ######### end resources #########
